/* This file has been generated by yabbler.js */
require.define({
"program": function(require, exports, module) {
var hasOwnProperty = require('hasOwnProperty');
var toString = require('toString');
var test = require('test');
test.print('DONE', 'info');

}}, ["hasOwnProperty", "toString", "test"]);