/* This file has been generated by yabbler.js */
require.define({
"program": function(require, exports, module) {
var a = require('a');
var test = require('test');
test.assert(exports.monkey == 10, 'monkeys permitted');
test.print('DONE', 'info');

}}, ["a", "test"]);