/* This file has been generated by yabbler.js */
require.define({
"program": function(require, exports, module) {
var test = require('test');
require('submodule/a');
test.print('DONE', 'info');

}}, ["test", "submodule/a"]);